<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Deity\PushPro\ViewModel\PushProSnippet $viewModel */
$viewModel = $block->getData('viewModel');
$pushProNotificationScript = $viewModel->getPushProCodeSnippet();
?>
<?php if ($pushProNotificationScript): ?>
    <script>
        window.__pushpro = {
            swPath: "<?php echo $block->escapeUrl($block->getViewFileUrl('Deity_PushPro::js/sw.js')); ?>",
        }
    </script>
    <?php echo /* @noEscape */ $pushProNotificationScript ?>
<?php endif; ?>
